using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.RMCSecurity.JAS;

[GenerateTypedNameReferences]
public sealed partial class JurisdictionalASWindow : DefaultWindow
{
    public JurisdictionalASWindow()
    {
        RobustXamlLoader.Load(this);

        JASChargeTabButton.OnPressed += OnChargeTabPressed;
        JASDetailsTabButton.OnPressed += OnDetailsTabPressed;
        JASWitnessIDTabButton.OnPressed += OnWitnessTabPressed;
        JASEvidenceIDTabButton.OnPressed += OnEvidenceTabPressed;

        ShowTab("JASDetailsView");
    }

    private void OnChargeTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ShowTab("JASChargeView");
    }

    private void OnDetailsTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ShowTab("JASDetailsView");
    }

    private void OnWitnessTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ShowTab("JASWitnessView");
    }

    private void OnEvidenceTabPressed(BaseButton.ButtonEventArgs obj)
    {
        ShowTab("JASEvidenceView");
    }

    private void ShowTab(string tabName)
    {
        JASChargeView.Visible = false;
        JASDetailsView.Visible = false;
        JASWitnessView.Visible = false;
        JASEvidenceView.Visible = false;
        switch (tabName)
        {
            case "JASChargeView":
                JASChargeView.Visible = true;
                break;
            case "JASDetailsView":
                JASDetailsView.Visible = true;
                break;
            case "JASWitnessView":
                JASWitnessView.Visible = true;
                break;
            case "JASEvidenceView":
                JASEvidenceView.Visible = true;
                break;
        }
    }
}
